name: DigitalOcean App Platform deployment
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/app_action@main
        with:
         app_name: taha
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
