name: DigitalOcean App Platform deployment
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/app_action@main
        with:
         app_name: taha
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: taha
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                    {
                      "name": "taha",
                      "repository": "registry.digitalocean.com/taha/taha",
                      "tag": "1"
                    },
                    {
                      "name": "taha-1",
                      "repository": "registry.digitalocean.com/taha/taha",
                      "tag": "1"
                    },
                  ]'
